In [3]:
import os
from scipy.io import wavfile
from shutil import copyfile
from sphfile import SPHFile
from WaveNetClassifier import WaveNetClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

Using TensorFlow backend.


In [2]:
# Copy folder structure without files

wav_base_dir = 'TRAIN_WAV'

for path, dirname, filename in os.walk('TRAIN'):
    path_array = path.split(os.sep)
    path_array[0] = wav_base_dir
    new_path = '/'.join(path_array)
    try:
        os.makedirs(new_path)
    except FileExistsError:
        # directory already exists
        pass

In [3]:
# Transform NIST Sphere Files to WAV and copy them to the TRAIN_WAV directory.

for path, dirname, filenames in os.walk('TRAIN'):
    for filename in filenames:
        if filename.endswith(".WAV"): 
            file_path = os.path.join(path, filename)
            path_array = file_path.split(os.sep)
            path_array[0] = wav_base_dir
            new_path = '/'.join(path_array)
            print(new_path)
            
            sph = SPHFile(file_path)
            sph.write_wav(new_path)

TRAIN_WAV/DR1/FCJF0/SA1.WAV
TRAIN_WAV/DR1/FCJF0/SA2.WAV
TRAIN_WAV/DR1/FCJF0/SI1027.WAV
TRAIN_WAV/DR1/FCJF0/SI1657.WAV
TRAIN_WAV/DR1/FCJF0/SI648.WAV
TRAIN_WAV/DR1/FCJF0/SX127.WAV
TRAIN_WAV/DR1/FCJF0/SX217.WAV
TRAIN_WAV/DR1/FCJF0/SX307.WAV
TRAIN_WAV/DR1/FCJF0/SX37.WAV
TRAIN_WAV/DR1/FCJF0/SX397.WAV
TRAIN_WAV/DR1/FDAW0/SA1.WAV
TRAIN_WAV/DR1/FDAW0/SA2.WAV
TRAIN_WAV/DR1/FDAW0/SI1271.WAV
TRAIN_WAV/DR1/FDAW0/SI1406.WAV
TRAIN_WAV/DR1/FDAW0/SI2036.WAV
TRAIN_WAV/DR1/FDAW0/SX146.WAV
TRAIN_WAV/DR1/FDAW0/SX236.WAV
TRAIN_WAV/DR1/FDAW0/SX326.WAV
TRAIN_WAV/DR1/FDAW0/SX416.WAV
TRAIN_WAV/DR1/FDAW0/SX56.WAV
TRAIN_WAV/DR1/FDML0/SA1.WAV
TRAIN_WAV/DR1/FDML0/SA2.WAV
TRAIN_WAV/DR1/FDML0/SI1149.WAV
TRAIN_WAV/DR1/FDML0/SI1779.WAV
TRAIN_WAV/DR1/FDML0/SI2075.WAV
TRAIN_WAV/DR1/FDML0/SX159.WAV
TRAIN_WAV/DR1/FDML0/SX249.WAV
TRAIN_WAV/DR1/FDML0/SX339.WAV
TRAIN_WAV/DR1/FDML0/SX429.WAV
TRAIN_WAV/DR1/FDML0/SX69.WAV
TRAIN_WAV/DR1/FECD0/SA1.WAV
TRAIN_WAV/DR1/FECD0/SA2.WAV
TRAIN_WAV/DR1/FECD0/SI1418.WAV
TRAIN_WAV/DR1/FECD0/

TRAIN_WAV/DR1/MRAI0/SX342.WAV
TRAIN_WAV/DR1/MRAI0/SX432.WAV
TRAIN_WAV/DR1/MRAI0/SX72.WAV
TRAIN_WAV/DR1/MRCG0/SA1.WAV
TRAIN_WAV/DR1/MRCG0/SA2.WAV
TRAIN_WAV/DR1/MRCG0/SI1428.WAV
TRAIN_WAV/DR1/MRCG0/SI2058.WAV
TRAIN_WAV/DR1/MRCG0/SI798.WAV
TRAIN_WAV/DR1/MRCG0/SX168.WAV
TRAIN_WAV/DR1/MRCG0/SX258.WAV
TRAIN_WAV/DR1/MRCG0/SX348.WAV
TRAIN_WAV/DR1/MRCG0/SX438.WAV
TRAIN_WAV/DR1/MRCG0/SX78.WAV
TRAIN_WAV/DR1/MRDD0/SA1.WAV
TRAIN_WAV/DR1/MRDD0/SA2.WAV
TRAIN_WAV/DR1/MRDD0/SI1050.WAV
TRAIN_WAV/DR1/MRDD0/SI1680.WAV
TRAIN_WAV/DR1/MRDD0/SI2310.WAV
TRAIN_WAV/DR1/MRDD0/SX150.WAV
TRAIN_WAV/DR1/MRDD0/SX240.WAV
TRAIN_WAV/DR1/MRDD0/SX277.WAV
TRAIN_WAV/DR1/MRDD0/SX330.WAV
TRAIN_WAV/DR1/MRDD0/SX60.WAV
TRAIN_WAV/DR1/MRSO0/SA1.WAV
TRAIN_WAV/DR1/MRSO0/SA2.WAV
TRAIN_WAV/DR1/MRSO0/SI1206.WAV
TRAIN_WAV/DR1/MRSO0/SI1659.WAV
TRAIN_WAV/DR1/MRSO0/SI2289.WAV
TRAIN_WAV/DR1/MRSO0/SX129.WAV
TRAIN_WAV/DR1/MRSO0/SX219.WAV
TRAIN_WAV/DR1/MRSO0/SX309.WAV
TRAIN_WAV/DR1/MRSO0/SX39.WAV
TRAIN_WAV/DR1/MRSO0/SX399.WAV
TRAIN_WAV/DR1/MRWS

TRAIN_WAV/DR2/FSCN0/SA2.WAV
TRAIN_WAV/DR2/FSCN0/SI1886.WAV
TRAIN_WAV/DR2/FSCN0/SI626.WAV
TRAIN_WAV/DR2/FSCN0/SI705.WAV
TRAIN_WAV/DR2/FSCN0/SX176.WAV
TRAIN_WAV/DR2/FSCN0/SX266.WAV
TRAIN_WAV/DR2/FSCN0/SX356.WAV
TRAIN_WAV/DR2/FSCN0/SX446.WAV
TRAIN_WAV/DR2/FSCN0/SX86.WAV
TRAIN_WAV/DR2/FSKL0/SA1.WAV
TRAIN_WAV/DR2/FSKL0/SA2.WAV
TRAIN_WAV/DR2/FSKL0/SI1529.WAV
TRAIN_WAV/DR2/FSKL0/SI2159.WAV
TRAIN_WAV/DR2/FSKL0/SI899.WAV
TRAIN_WAV/DR2/FSKL0/SX179.WAV
TRAIN_WAV/DR2/FSKL0/SX269.WAV
TRAIN_WAV/DR2/FSKL0/SX359.WAV
TRAIN_WAV/DR2/FSKL0/SX449.WAV
TRAIN_WAV/DR2/FSKL0/SX89.WAV
TRAIN_WAV/DR2/FSRH0/SA1.WAV
TRAIN_WAV/DR2/FSRH0/SA2.WAV
TRAIN_WAV/DR2/FSRH0/SI1719.WAV
TRAIN_WAV/DR2/FSRH0/SI1931.WAV
TRAIN_WAV/DR2/FSRH0/SI671.WAV
TRAIN_WAV/DR2/FSRH0/SX131.WAV
TRAIN_WAV/DR2/FSRH0/SX221.WAV
TRAIN_WAV/DR2/FSRH0/SX311.WAV
TRAIN_WAV/DR2/FSRH0/SX401.WAV
TRAIN_WAV/DR2/FSRH0/SX41.WAV
TRAIN_WAV/DR2/FTMG0/SA1.WAV
TRAIN_WAV/DR2/FTMG0/SA2.WAV
TRAIN_WAV/DR2/FTMG0/SI1532.WAV
TRAIN_WAV/DR2/FTMG0/SI2162.WAV
TRAIN_WAV/DR2/FTMG0/

TRAIN_WAV/DR2/MKAJ0/SA2.WAV
TRAIN_WAV/DR2/MKAJ0/SI1414.WAV
TRAIN_WAV/DR2/MKAJ0/SI2044.WAV
TRAIN_WAV/DR2/MKAJ0/SI784.WAV
TRAIN_WAV/DR2/MKAJ0/SX154.WAV
TRAIN_WAV/DR2/MKAJ0/SX244.WAV
TRAIN_WAV/DR2/MKAJ0/SX334.WAV
TRAIN_WAV/DR2/MKAJ0/SX424.WAV
TRAIN_WAV/DR2/MKAJ0/SX64.WAV
TRAIN_WAV/DR2/MKDT0/SA1.WAV
TRAIN_WAV/DR2/MKDT0/SA2.WAV
TRAIN_WAV/DR2/MKDT0/SI2153.WAV
TRAIN_WAV/DR2/MKDT0/SI814.WAV
TRAIN_WAV/DR2/MKDT0/SI893.WAV
TRAIN_WAV/DR2/MKDT0/SX173.WAV
TRAIN_WAV/DR2/MKDT0/SX263.WAV
TRAIN_WAV/DR2/MKDT0/SX353.WAV
TRAIN_WAV/DR2/MKDT0/SX443.WAV
TRAIN_WAV/DR2/MKDT0/SX83.WAV
TRAIN_WAV/DR2/MKJO0/SA1.WAV
TRAIN_WAV/DR2/MKJO0/SA2.WAV
TRAIN_WAV/DR2/MKJO0/SI1517.WAV
TRAIN_WAV/DR2/MKJO0/SI2147.WAV
TRAIN_WAV/DR2/MKJO0/SI887.WAV
TRAIN_WAV/DR2/MKJO0/SX167.WAV
TRAIN_WAV/DR2/MKJO0/SX257.WAV
TRAIN_WAV/DR2/MKJO0/SX424.WAV
TRAIN_WAV/DR2/MKJO0/SX437.WAV
TRAIN_WAV/DR2/MKJO0/SX77.WAV
TRAIN_WAV/DR2/MMAA0/SA1.WAV
TRAIN_WAV/DR2/MMAA0/SA2.WAV
TRAIN_WAV/DR2/MMAA0/SI1588.WAV
TRAIN_WAV/DR2/MMAA0/SI2105.WAV
TRAIN_WAV/DR2/MMAA0/

TRAIN_WAV/DR3/FALK0/SI658.WAV
TRAIN_WAV/DR3/FALK0/SX186.WAV
TRAIN_WAV/DR3/FALK0/SX276.WAV
TRAIN_WAV/DR3/FALK0/SX366.WAV
TRAIN_WAV/DR3/FALK0/SX6.WAV
TRAIN_WAV/DR3/FALK0/SX96.WAV
TRAIN_WAV/DR3/FCKE0/SA1.WAV
TRAIN_WAV/DR3/FCKE0/SA2.WAV
TRAIN_WAV/DR3/FCKE0/SI1111.WAV
TRAIN_WAV/DR3/FCKE0/SI1741.WAV
TRAIN_WAV/DR3/FCKE0/SI481.WAV
TRAIN_WAV/DR3/FCKE0/SX121.WAV
TRAIN_WAV/DR3/FCKE0/SX211.WAV
TRAIN_WAV/DR3/FCKE0/SX301.WAV
TRAIN_WAV/DR3/FCKE0/SX31.WAV
TRAIN_WAV/DR3/FCKE0/SX391.WAV
TRAIN_WAV/DR3/FCMG0/SA1.WAV
TRAIN_WAV/DR3/FCMG0/SA2.WAV
TRAIN_WAV/DR3/FCMG0/SI1142.WAV
TRAIN_WAV/DR3/FCMG0/SI1242.WAV
TRAIN_WAV/DR3/FCMG0/SI1872.WAV
TRAIN_WAV/DR3/FCMG0/SX162.WAV
TRAIN_WAV/DR3/FCMG0/SX252.WAV
TRAIN_WAV/DR3/FCMG0/SX342.WAV
TRAIN_WAV/DR3/FCMG0/SX432.WAV
TRAIN_WAV/DR3/FCMG0/SX72.WAV
TRAIN_WAV/DR3/FDFB0/SA1.WAV
TRAIN_WAV/DR3/FDFB0/SA2.WAV
TRAIN_WAV/DR3/FDFB0/SI1318.WAV
TRAIN_WAV/DR3/FDFB0/SI1948.WAV
TRAIN_WAV/DR3/FDFB0/SI2010.WAV
TRAIN_WAV/DR3/FDFB0/SX148.WAV
TRAIN_WAV/DR3/FDFB0/SX238.WAV
TRAIN_WAV/DR3/FDFB0

TRAIN_WAV/DR3/MDBB1/SX286.WAV
TRAIN_WAV/DR3/MDBB1/SX376.WAV
TRAIN_WAV/DR3/MDDC0/SA1.WAV
TRAIN_WAV/DR3/MDDC0/SA2.WAV
TRAIN_WAV/DR3/MDDC0/SI1419.WAV
TRAIN_WAV/DR3/MDDC0/SI2049.WAV
TRAIN_WAV/DR3/MDDC0/SI789.WAV
TRAIN_WAV/DR3/MDDC0/SX159.WAV
TRAIN_WAV/DR3/MDDC0/SX249.WAV
TRAIN_WAV/DR3/MDDC0/SX339.WAV
TRAIN_WAV/DR3/MDDC0/SX429.WAV
TRAIN_WAV/DR3/MDDC0/SX69.WAV
TRAIN_WAV/DR3/MDEF0/SA1.WAV
TRAIN_WAV/DR3/MDEF0/SA2.WAV
TRAIN_WAV/DR3/MDEF0/SI1123.WAV
TRAIN_WAV/DR3/MDEF0/SI1563.WAV
TRAIN_WAV/DR3/MDEF0/SI2193.WAV
TRAIN_WAV/DR3/MDEF0/SX123.WAV
TRAIN_WAV/DR3/MDEF0/SX213.WAV
TRAIN_WAV/DR3/MDEF0/SX303.WAV
TRAIN_WAV/DR3/MDEF0/SX33.WAV
TRAIN_WAV/DR3/MDEF0/SX393.WAV
TRAIN_WAV/DR3/MDHS0/SA1.WAV
TRAIN_WAV/DR3/MDHS0/SA2.WAV
TRAIN_WAV/DR3/MDHS0/SI1530.WAV
TRAIN_WAV/DR3/MDHS0/SI2160.WAV
TRAIN_WAV/DR3/MDHS0/SI900.WAV
TRAIN_WAV/DR3/MDHS0/SX180.WAV
TRAIN_WAV/DR3/MDHS0/SX270.WAV
TRAIN_WAV/DR3/MDHS0/SX360.WAV
TRAIN_WAV/DR3/MDHS0/SX450.WAV
TRAIN_WAV/DR3/MDHS0/SX90.WAV
TRAIN_WAV/DR3/MDJM0/SA1.WAV
TRAIN_WAV/DR3/MDJM0/

TRAIN_WAV/DR3/MRBC0/SX329.WAV
TRAIN_WAV/DR3/MRBC0/SX419.WAV
TRAIN_WAV/DR3/MRBC0/SX59.WAV
TRAIN_WAV/DR3/MRDS0/SA1.WAV
TRAIN_WAV/DR3/MRDS0/SA2.WAV
TRAIN_WAV/DR3/MRDS0/SI1167.WAV
TRAIN_WAV/DR3/MRDS0/SI1797.WAV
TRAIN_WAV/DR3/MRDS0/SI537.WAV
TRAIN_WAV/DR3/MRDS0/SX177.WAV
TRAIN_WAV/DR3/MRDS0/SX267.WAV
TRAIN_WAV/DR3/MRDS0/SX357.WAV
TRAIN_WAV/DR3/MRDS0/SX447.WAV
TRAIN_WAV/DR3/MRDS0/SX87.WAV
TRAIN_WAV/DR3/MREE0/SA1.WAV
TRAIN_WAV/DR3/MREE0/SA2.WAV
TRAIN_WAV/DR3/MREE0/SI1104.WAV
TRAIN_WAV/DR3/MREE0/SI1734.WAV
TRAIN_WAV/DR3/MREE0/SI1959.WAV
TRAIN_WAV/DR3/MREE0/SX114.WAV
TRAIN_WAV/DR3/MREE0/SX204.WAV
TRAIN_WAV/DR3/MREE0/SX24.WAV
TRAIN_WAV/DR3/MREE0/SX294.WAV
TRAIN_WAV/DR3/MREE0/SX384.WAV
TRAIN_WAV/DR3/MREH1/SA1.WAV
TRAIN_WAV/DR3/MREH1/SA2.WAV
TRAIN_WAV/DR3/MREH1/SI1599.WAV
TRAIN_WAV/DR3/MREH1/SI2229.WAV
TRAIN_WAV/DR3/MREH1/SI969.WAV
TRAIN_WAV/DR3/MREH1/SX159.WAV
TRAIN_WAV/DR3/MREH1/SX249.WAV
TRAIN_WAV/DR3/MREH1/SX339.WAV
TRAIN_WAV/DR3/MREH1/SX429.WAV
TRAIN_WAV/DR3/MREH1/SX69.WAV
TRAIN_WAV/DR3/MRJB1

TRAIN_WAV/DR4/FPAF0/SI2314.WAV
TRAIN_WAV/DR4/FPAF0/SX154.WAV
TRAIN_WAV/DR4/FPAF0/SX244.WAV
TRAIN_WAV/DR4/FPAF0/SX334.WAV
TRAIN_WAV/DR4/FPAF0/SX424.WAV
TRAIN_WAV/DR4/FPAF0/SX64.WAV
TRAIN_WAV/DR4/FSAK0/SA1.WAV
TRAIN_WAV/DR4/FSAK0/SA2.WAV
TRAIN_WAV/DR4/FSAK0/SI1300.WAV
TRAIN_WAV/DR4/FSAK0/SI1930.WAV
TRAIN_WAV/DR4/FSAK0/SI670.WAV
TRAIN_WAV/DR4/FSAK0/SX130.WAV
TRAIN_WAV/DR4/FSAK0/SX220.WAV
TRAIN_WAV/DR4/FSAK0/SX310.WAV
TRAIN_WAV/DR4/FSAK0/SX40.WAV
TRAIN_WAV/DR4/FSAK0/SX400.WAV
TRAIN_WAV/DR4/FSSB0/SA1.WAV
TRAIN_WAV/DR4/FSSB0/SA2.WAV
TRAIN_WAV/DR4/FSSB0/SI1082.WAV
TRAIN_WAV/DR4/FSSB0/SI1712.WAV
TRAIN_WAV/DR4/FSSB0/SI2342.WAV
TRAIN_WAV/DR4/FSSB0/SX182.WAV
TRAIN_WAV/DR4/FSSB0/SX272.WAV
TRAIN_WAV/DR4/FSSB0/SX362.WAV
TRAIN_WAV/DR4/FSSB0/SX452.WAV
TRAIN_WAV/DR4/FSSB0/SX92.WAV
TRAIN_WAV/DR4/MAEB0/SA1.WAV
TRAIN_WAV/DR4/MAEB0/SA2.WAV
TRAIN_WAV/DR4/MAEB0/SI1411.WAV
TRAIN_WAV/DR4/MAEB0/SI2250.WAV
TRAIN_WAV/DR4/MAEB0/SI990.WAV
TRAIN_WAV/DR4/MAEB0/SX180.WAV
TRAIN_WAV/DR4/MAEB0/SX270.WAV
TRAIN_WAV/DR4/MAE

TRAIN_WAV/DR4/MJXL0/SA2.WAV
TRAIN_WAV/DR4/MJXL0/SI1172.WAV
TRAIN_WAV/DR4/MJXL0/SI1795.WAV
TRAIN_WAV/DR4/MJXL0/SI542.WAV
TRAIN_WAV/DR4/MJXL0/SX182.WAV
TRAIN_WAV/DR4/MJXL0/SX272.WAV
TRAIN_WAV/DR4/MJXL0/SX362.WAV
TRAIN_WAV/DR4/MJXL0/SX452.WAV
TRAIN_WAV/DR4/MJXL0/SX92.WAV
TRAIN_WAV/DR4/MKAM0/SA1.WAV
TRAIN_WAV/DR4/MKAM0/SA2.WAV
TRAIN_WAV/DR4/MKAM0/SI1250.WAV
TRAIN_WAV/DR4/MKAM0/SI1316.WAV
TRAIN_WAV/DR4/MKAM0/SI1465.WAV
TRAIN_WAV/DR4/MKAM0/SX146.WAV
TRAIN_WAV/DR4/MKAM0/SX236.WAV
TRAIN_WAV/DR4/MKAM0/SX326.WAV
TRAIN_WAV/DR4/MKAM0/SX416.WAV
TRAIN_WAV/DR4/MKAM0/SX56.WAV
TRAIN_WAV/DR4/MLBC0/SA1.WAV
TRAIN_WAV/DR4/MLBC0/SA2.WAV
TRAIN_WAV/DR4/MLBC0/SI1239.WAV
TRAIN_WAV/DR4/MLBC0/SI1869.WAV
TRAIN_WAV/DR4/MLBC0/SI609.WAV
TRAIN_WAV/DR4/MLBC0/SX159.WAV
TRAIN_WAV/DR4/MLBC0/SX249.WAV
TRAIN_WAV/DR4/MLBC0/SX339.WAV
TRAIN_WAV/DR4/MLBC0/SX429.WAV
TRAIN_WAV/DR4/MLBC0/SX69.WAV
TRAIN_WAV/DR4/MLEL0/SA1.WAV
TRAIN_WAV/DR4/MLEL0/SA2.WAV
TRAIN_WAV/DR4/MLEL0/SI1246.WAV
TRAIN_WAV/DR4/MLEL0/SI1876.WAV
TRAIN_WAV/DR4/MLEL

TRAIN_WAV/DR5/FCDR1/SI1186.WAV
TRAIN_WAV/DR5/FCDR1/SI1816.WAV
TRAIN_WAV/DR5/FCDR1/SI556.WAV
TRAIN_WAV/DR5/FCDR1/SX106.WAV
TRAIN_WAV/DR5/FCDR1/SX16.WAV
TRAIN_WAV/DR5/FCDR1/SX196.WAV
TRAIN_WAV/DR5/FCDR1/SX286.WAV
TRAIN_WAV/DR5/FCDR1/SX376.WAV
TRAIN_WAV/DR5/FDMY0/SA1.WAV
TRAIN_WAV/DR5/FDMY0/SA2.WAV
TRAIN_WAV/DR5/FDMY0/SI1197.WAV
TRAIN_WAV/DR5/FDMY0/SI567.WAV
TRAIN_WAV/DR5/FDMY0/SI714.WAV
TRAIN_WAV/DR5/FDMY0/SX117.WAV
TRAIN_WAV/DR5/FDMY0/SX207.WAV
TRAIN_WAV/DR5/FDMY0/SX27.WAV
TRAIN_WAV/DR5/FDMY0/SX297.WAV
TRAIN_WAV/DR5/FDMY0/SX387.WAV
TRAIN_WAV/DR5/FDTD0/SA1.WAV
TRAIN_WAV/DR5/FDTD0/SA2.WAV
TRAIN_WAV/DR5/FDTD0/SI1561.WAV
TRAIN_WAV/DR5/FDTD0/SI2191.WAV
TRAIN_WAV/DR5/FDTD0/SI931.WAV
TRAIN_WAV/DR5/FDTD0/SX121.WAV
TRAIN_WAV/DR5/FDTD0/SX211.WAV
TRAIN_WAV/DR5/FDTD0/SX301.WAV
TRAIN_WAV/DR5/FDTD0/SX321.WAV
TRAIN_WAV/DR5/FDTD0/SX391.WAV
TRAIN_WAV/DR5/FEAR0/SA1.WAV
TRAIN_WAV/DR5/FEAR0/SA2.WAV
TRAIN_WAV/DR5/FEAR0/SI1252.WAV
TRAIN_WAV/DR5/FEAR0/SI1882.WAV
TRAIN_WAV/DR5/FEAR0/SI622.WAV
TRAIN_WAV/DR5/FEA

TRAIN_WAV/DR5/MDWH0/SI1168.WAV
TRAIN_WAV/DR5/MDWH0/SI1925.WAV
TRAIN_WAV/DR5/MDWH0/SI665.WAV
TRAIN_WAV/DR5/MDWH0/SX125.WAV
TRAIN_WAV/DR5/MDWH0/SX215.WAV
TRAIN_WAV/DR5/MDWH0/SX305.WAV
TRAIN_WAV/DR5/MDWH0/SX35.WAV
TRAIN_WAV/DR5/MDWH0/SX395.WAV
TRAIN_WAV/DR5/MEGJ0/SA1.WAV
TRAIN_WAV/DR5/MEGJ0/SA2.WAV
TRAIN_WAV/DR5/MEGJ0/SI1337.WAV
TRAIN_WAV/DR5/MEGJ0/SI1967.WAV
TRAIN_WAV/DR5/MEGJ0/SI707.WAV
TRAIN_WAV/DR5/MEGJ0/SX167.WAV
TRAIN_WAV/DR5/MEGJ0/SX257.WAV
TRAIN_WAV/DR5/MEGJ0/SX3.WAV
TRAIN_WAV/DR5/MEGJ0/SX437.WAV
TRAIN_WAV/DR5/MEGJ0/SX77.WAV
TRAIN_WAV/DR5/MEWM0/SA1.WAV
TRAIN_WAV/DR5/MEWM0/SA2.WAV
TRAIN_WAV/DR5/MEWM0/SI1348.WAV
TRAIN_WAV/DR5/MEWM0/SI1978.WAV
TRAIN_WAV/DR5/MEWM0/SI718.WAV
TRAIN_WAV/DR5/MEWM0/SX178.WAV
TRAIN_WAV/DR5/MEWM0/SX268.WAV
TRAIN_WAV/DR5/MEWM0/SX358.WAV
TRAIN_WAV/DR5/MEWM0/SX448.WAV
TRAIN_WAV/DR5/MEWM0/SX88.WAV
TRAIN_WAV/DR5/MFER0/SA1.WAV
TRAIN_WAV/DR5/MFER0/SA2.WAV
TRAIN_WAV/DR5/MFER0/SI1492.WAV
TRAIN_WAV/DR5/MFER0/SI2122.WAV
TRAIN_WAV/DR5/MFER0/SI862.WAV
TRAIN_WAV/DR5/MFER0

TRAIN_WAV/DR5/MSDH0/SI980.WAV
TRAIN_WAV/DR5/MSDH0/SX170.WAV
TRAIN_WAV/DR5/MSDH0/SX260.WAV
TRAIN_WAV/DR5/MSDH0/SX350.WAV
TRAIN_WAV/DR5/MSDH0/SX440.WAV
TRAIN_WAV/DR5/MSDH0/SX80.WAV
TRAIN_WAV/DR5/MSEM1/SA1.WAV
TRAIN_WAV/DR5/MSEM1/SA2.WAV
TRAIN_WAV/DR5/MSEM1/SI1440.WAV
TRAIN_WAV/DR5/MSEM1/SI2070.WAV
TRAIN_WAV/DR5/MSEM1/SI810.WAV
TRAIN_WAV/DR5/MSEM1/SX180.WAV
TRAIN_WAV/DR5/MSEM1/SX270.WAV
TRAIN_WAV/DR5/MSEM1/SX360.WAV
TRAIN_WAV/DR5/MSEM1/SX450.WAV
TRAIN_WAV/DR5/MSEM1/SX90.WAV
TRAIN_WAV/DR5/MSRR0/SA1.WAV
TRAIN_WAV/DR5/MSRR0/SA2.WAV
TRAIN_WAV/DR5/MSRR0/SI1131.WAV
TRAIN_WAV/DR5/MSRR0/SI1761.WAV
TRAIN_WAV/DR5/MSRR0/SI501.WAV
TRAIN_WAV/DR5/MSRR0/SX141.WAV
TRAIN_WAV/DR5/MSRR0/SX231.WAV
TRAIN_WAV/DR5/MSRR0/SX30.WAV
TRAIN_WAV/DR5/MSRR0/SX411.WAV
TRAIN_WAV/DR5/MSRR0/SX51.WAV
TRAIN_WAV/DR5/MTAT0/SA1.WAV
TRAIN_WAV/DR5/MTAT0/SA2.WAV
TRAIN_WAV/DR5/MTAT0/SI1110.WAV
TRAIN_WAV/DR5/MTAT0/SI1740.WAV
TRAIN_WAV/DR5/MTAT0/SI811.WAV
TRAIN_WAV/DR5/MTAT0/SX120.WAV
TRAIN_WAV/DR5/MTAT0/SX210.WAV
TRAIN_WAV/DR5/MTAT0/

TRAIN_WAV/DR6/MDRD0/SI1382.WAV
TRAIN_WAV/DR6/MDRD0/SI2012.WAV
TRAIN_WAV/DR6/MDRD0/SI752.WAV
TRAIN_WAV/DR6/MDRD0/SX122.WAV
TRAIN_WAV/DR6/MDRD0/SX212.WAV
TRAIN_WAV/DR6/MDRD0/SX302.WAV
TRAIN_WAV/DR6/MDRD0/SX32.WAV
TRAIN_WAV/DR6/MDRD0/SX392.WAV
TRAIN_WAV/DR6/MEAL0/SA1.WAV
TRAIN_WAV/DR6/MEAL0/SA2.WAV
TRAIN_WAV/DR6/MEAL0/SI1547.WAV
TRAIN_WAV/DR6/MEAL0/SI2177.WAV
TRAIN_WAV/DR6/MEAL0/SI917.WAV
TRAIN_WAV/DR6/MEAL0/SX107.WAV
TRAIN_WAV/DR6/MEAL0/SX197.WAV
TRAIN_WAV/DR6/MEAL0/SX287.WAV
TRAIN_WAV/DR6/MEAL0/SX347.WAV
TRAIN_WAV/DR6/MEAL0/SX377.WAV
TRAIN_WAV/DR6/MEJL0/SA1.WAV
TRAIN_WAV/DR6/MEJL0/SA2.WAV
TRAIN_WAV/DR6/MEJL0/SI1592.WAV
TRAIN_WAV/DR6/MEJL0/SI1654.WAV
TRAIN_WAV/DR6/MEJL0/SI962.WAV
TRAIN_WAV/DR6/MEJL0/SX152.WAV
TRAIN_WAV/DR6/MEJL0/SX242.WAV
TRAIN_WAV/DR6/MEJL0/SX332.WAV
TRAIN_WAV/DR6/MEJL0/SX422.WAV
TRAIN_WAV/DR6/MEJL0/SX62.WAV
TRAIN_WAV/DR6/MESJ0/SA1.WAV
TRAIN_WAV/DR6/MESJ0/SA2.WAV
TRAIN_WAV/DR6/MESJ0/SI2039.WAV
TRAIN_WAV/DR6/MESJ0/SI2257.WAV
TRAIN_WAV/DR6/MESJ0/SI997.WAV
TRAIN_WAV/DR6/ME

TRAIN_WAV/DR7/FMAH1/SX429.WAV
TRAIN_WAV/DR7/FMAH1/SX69.WAV
TRAIN_WAV/DR7/FMKC0/SA1.WAV
TRAIN_WAV/DR7/FMKC0/SA2.WAV
TRAIN_WAV/DR7/FMKC0/SI1041.WAV
TRAIN_WAV/DR7/FMKC0/SI1072.WAV
TRAIN_WAV/DR7/FMKC0/SI1702.WAV
TRAIN_WAV/DR7/FMKC0/SX172.WAV
TRAIN_WAV/DR7/FMKC0/SX262.WAV
TRAIN_WAV/DR7/FMKC0/SX352.WAV
TRAIN_WAV/DR7/FMKC0/SX442.WAV
TRAIN_WAV/DR7/FMKC0/SX82.WAV
TRAIN_WAV/DR7/FPAB1/SA1.WAV
TRAIN_WAV/DR7/FPAB1/SA2.WAV
TRAIN_WAV/DR7/FPAB1/SI1471.WAV
TRAIN_WAV/DR7/FPAB1/SI2101.WAV
TRAIN_WAV/DR7/FPAB1/SI841.WAV
TRAIN_WAV/DR7/FPAB1/SX121.WAV
TRAIN_WAV/DR7/FPAB1/SX211.WAV
TRAIN_WAV/DR7/FPAB1/SX301.WAV
TRAIN_WAV/DR7/FPAB1/SX31.WAV
TRAIN_WAV/DR7/FPAB1/SX391.WAV
TRAIN_WAV/DR7/FPAC0/SA1.WAV
TRAIN_WAV/DR7/FPAC0/SA2.WAV
TRAIN_WAV/DR7/FPAC0/SI1921.WAV
TRAIN_WAV/DR7/FPAC0/SI2011.WAV
TRAIN_WAV/DR7/FPAC0/SI661.WAV
TRAIN_WAV/DR7/FPAC0/SX121.WAV
TRAIN_WAV/DR7/FPAC0/SX211.WAV
TRAIN_WAV/DR7/FPAC0/SX301.WAV
TRAIN_WAV/DR7/FPAC0/SX31.WAV
TRAIN_WAV/DR7/FPAC0/SX391.WAV
TRAIN_WAV/DR7/FREH0/SA1.WAV
TRAIN_WAV/DR7/FREH0/S

TRAIN_WAV/DR7/MGAW0/SI535.WAV
TRAIN_WAV/DR7/MGAW0/SX175.WAV
TRAIN_WAV/DR7/MGAW0/SX265.WAV
TRAIN_WAV/DR7/MGAW0/SX355.WAV
TRAIN_WAV/DR7/MGAW0/SX445.WAV
TRAIN_WAV/DR7/MGAW0/SX85.WAV
TRAIN_WAV/DR7/MGSL0/SA1.WAV
TRAIN_WAV/DR7/MGSL0/SA2.WAV
TRAIN_WAV/DR7/MGSL0/SI1164.WAV
TRAIN_WAV/DR7/MGSL0/SI534.WAV
TRAIN_WAV/DR7/MGSL0/SI797.WAV
TRAIN_WAV/DR7/MGSL0/SX174.WAV
TRAIN_WAV/DR7/MGSL0/SX264.WAV
TRAIN_WAV/DR7/MGSL0/SX354.WAV
TRAIN_WAV/DR7/MGSL0/SX444.WAV
TRAIN_WAV/DR7/MGSL0/SX84.WAV
TRAIN_WAV/DR7/MHBS0/SA1.WAV
TRAIN_WAV/DR7/MHBS0/SA2.WAV
TRAIN_WAV/DR7/MHBS0/SI1575.WAV
TRAIN_WAV/DR7/MHBS0/SI2205.WAV
TRAIN_WAV/DR7/MHBS0/SI945.WAV
TRAIN_WAV/DR7/MHBS0/SX135.WAV
TRAIN_WAV/DR7/MHBS0/SX225.WAV
TRAIN_WAV/DR7/MHBS0/SX315.WAV
TRAIN_WAV/DR7/MHBS0/SX405.WAV
TRAIN_WAV/DR7/MHBS0/SX45.WAV
TRAIN_WAV/DR7/MHXL0/SA1.WAV
TRAIN_WAV/DR7/MHXL0/SA2.WAV
TRAIN_WAV/DR7/MHXL0/SI1772.WAV
TRAIN_WAV/DR7/MHXL0/SI512.WAV
TRAIN_WAV/DR7/MHXL0/SI612.WAV
TRAIN_WAV/DR7/MHXL0/SX152.WAV
TRAIN_WAV/DR7/MHXL0/SX242.WAV
TRAIN_WAV/DR7/MHXL0/S

TRAIN_WAV/DR7/MTLC0/SX397.WAV
TRAIN_WAV/DR7/MTML0/SA1.WAV
TRAIN_WAV/DR7/MTML0/SA2.WAV
TRAIN_WAV/DR7/MTML0/SI1065.WAV
TRAIN_WAV/DR7/MTML0/SI1695.WAV
TRAIN_WAV/DR7/MTML0/SI2325.WAV
TRAIN_WAV/DR7/MTML0/SX165.WAV
TRAIN_WAV/DR7/MTML0/SX255.WAV
TRAIN_WAV/DR7/MTML0/SX345.WAV
TRAIN_WAV/DR7/MTML0/SX435.WAV
TRAIN_WAV/DR7/MTML0/SX75.WAV
TRAIN_WAV/DR7/MTMN0/SA1.WAV
TRAIN_WAV/DR7/MTMN0/SA2.WAV
TRAIN_WAV/DR7/MTMN0/SI1064.WAV
TRAIN_WAV/DR7/MTMN0/SI2324.WAV
TRAIN_WAV/DR7/MTMN0/SI582.WAV
TRAIN_WAV/DR7/MTMN0/SX164.WAV
TRAIN_WAV/DR7/MTMN0/SX254.WAV
TRAIN_WAV/DR7/MTMN0/SX344.WAV
TRAIN_WAV/DR7/MTMN0/SX434.WAV
TRAIN_WAV/DR7/MTMN0/SX74.WAV
TRAIN_WAV/DR7/MTPR0/SA1.WAV
TRAIN_WAV/DR7/MTPR0/SA2.WAV
TRAIN_WAV/DR7/MTPR0/SI1600.WAV
TRAIN_WAV/DR7/MTPR0/SI2230.WAV
TRAIN_WAV/DR7/MTPR0/SI506.WAV
TRAIN_WAV/DR7/MTPR0/SX160.WAV
TRAIN_WAV/DR7/MTPR0/SX250.WAV
TRAIN_WAV/DR7/MTPR0/SX340.WAV
TRAIN_WAV/DR7/MTPR0/SX430.WAV
TRAIN_WAV/DR7/MTPR0/SX70.WAV
TRAIN_WAV/DR7/MTWH1/SA1.WAV
TRAIN_WAV/DR7/MTWH1/SA2.WAV
TRAIN_WAV/DR7/MTWH1/SI

TRAIN_WAV/DR8/MTCS0/SA1.WAV
TRAIN_WAV/DR8/MTCS0/SA2.WAV
TRAIN_WAV/DR8/MTCS0/SI1972.WAV
TRAIN_WAV/DR8/MTCS0/SI2265.WAV
TRAIN_WAV/DR8/MTCS0/SI712.WAV
TRAIN_WAV/DR8/MTCS0/SX172.WAV
TRAIN_WAV/DR8/MTCS0/SX262.WAV
TRAIN_WAV/DR8/MTCS0/SX352.WAV
TRAIN_WAV/DR8/MTCS0/SX442.WAV
TRAIN_WAV/DR8/MTCS0/SX82.WAV


In [4]:
fs, data = wavfile.read('TRAIN_WAV/DR3/FGRW0/SA1.WAV')
display(len(data))

fs, data = wavfile.read('TRAIN_WAV/DR3/FJLG0/SA1.WAV')
display(len(data))

fs, data = wavfile.read('TRAIN_WAV/DR6/MSAT1/SA1.WAV')
display(len(data))

68199

55808

54682

In [6]:
# Copy the SA1.WAV files with the identifier folders to SA1_UNIFORM directory.

SA1_base_dir = 'SA1_UNIFORM'

for path, dirname, filenames in os.walk('TRAIN_WAV'):
    for filename in filenames:
        if filename.endswith("SA1.WAV"):
            file_path = os.path.join(path, filename)
            path_array = file_path.split(os.sep)
            path_array[0] = SA1_base_dir
            try:
                os.makedirs(path_array[0] + "/" + path_array[-2])
            except FileExistsError:
                # directory already exists
                pass
            new_path = path_array[0] + "/" + path_array[-2] + "/" + filename
            print(new_path)
            copyfile(file_path, new_path)

SA1_UNIFORM/FCJF0/SA1.WAV
SA1_UNIFORM/FDAW0/SA1.WAV
SA1_UNIFORM/FDML0/SA1.WAV
SA1_UNIFORM/FECD0/SA1.WAV
SA1_UNIFORM/FETB0/SA1.WAV
SA1_UNIFORM/FJSP0/SA1.WAV
SA1_UNIFORM/FKFB0/SA1.WAV
SA1_UNIFORM/FMEM0/SA1.WAV
SA1_UNIFORM/FSAH0/SA1.WAV
SA1_UNIFORM/FSJK1/SA1.WAV
SA1_UNIFORM/FSMA0/SA1.WAV
SA1_UNIFORM/FTBR0/SA1.WAV
SA1_UNIFORM/FVFB0/SA1.WAV
SA1_UNIFORM/FVMH0/SA1.WAV
SA1_UNIFORM/MCPM0/SA1.WAV
SA1_UNIFORM/MDAC0/SA1.WAV
SA1_UNIFORM/MDPK0/SA1.WAV
SA1_UNIFORM/MEDR0/SA1.WAV
SA1_UNIFORM/MGRL0/SA1.WAV
SA1_UNIFORM/MJEB1/SA1.WAV
SA1_UNIFORM/MJWT0/SA1.WAV
SA1_UNIFORM/MKLS0/SA1.WAV
SA1_UNIFORM/MKLW0/SA1.WAV
SA1_UNIFORM/MMGG0/SA1.WAV
SA1_UNIFORM/MMRP0/SA1.WAV
SA1_UNIFORM/MPGH0/SA1.WAV
SA1_UNIFORM/MPGR0/SA1.WAV
SA1_UNIFORM/MPSW0/SA1.WAV
SA1_UNIFORM/MRAI0/SA1.WAV
SA1_UNIFORM/MRCG0/SA1.WAV
SA1_UNIFORM/MRDD0/SA1.WAV
SA1_UNIFORM/MRSO0/SA1.WAV
SA1_UNIFORM/MRWS0/SA1.WAV
SA1_UNIFORM/MTJS0/SA1.WAV
SA1_UNIFORM/MTPF0/SA1.WAV
SA1_UNIFORM/MTRR0/SA1.WAV
SA1_UNIFORM/MWAD0/SA1.WAV
SA1_UNIFORM/MWAR0/SA1.WAV
SA1_UNIFORM/

SA1_UNIFORM/FMJU0/SA1.WAV
SA1_UNIFORM/FPAD0/SA1.WAV
SA1_UNIFORM/FRJB0/SA1.WAV
SA1_UNIFORM/FSBK0/SA1.WAV
SA1_UNIFORM/FSDJ0/SA1.WAV
SA1_UNIFORM/FSGF0/SA1.WAV
SA1_UNIFORM/FTAJ0/SA1.WAV
SA1_UNIFORM/MABC0/SA1.WAV
SA1_UNIFORM/MAJP0/SA1.WAV
SA1_UNIFORM/MBMA1/SA1.WAV
SA1_UNIFORM/MCAE0/SA1.WAV
SA1_UNIFORM/MDRD0/SA1.WAV
SA1_UNIFORM/MEAL0/SA1.WAV
SA1_UNIFORM/MEJL0/SA1.WAV
SA1_UNIFORM/MESJ0/SA1.WAV
SA1_UNIFORM/MJRK0/SA1.WAV
SA1_UNIFORM/MKES0/SA1.WAV
SA1_UNIFORM/MKLN0/SA1.WAV
SA1_UNIFORM/MMDB0/SA1.WAV
SA1_UNIFORM/MPGR1/SA1.WAV
SA1_UNIFORM/MRMB0/SA1.WAV
SA1_UNIFORM/MRXB0/SA1.WAV
SA1_UNIFORM/MSAT1/SA1.WAV
SA1_UNIFORM/MSDS0/SA1.WAV
SA1_UNIFORM/MSJK0/SA1.WAV
SA1_UNIFORM/MSMR0/SA1.WAV
SA1_UNIFORM/MSVS0/SA1.WAV
SA1_UNIFORM/MTJU0/SA1.WAV
SA1_UNIFORM/MTXS0/SA1.WAV
SA1_UNIFORM/FBLV0/SA1.WAV
SA1_UNIFORM/FCJS0/SA1.WAV
SA1_UNIFORM/FCRZ0/SA1.WAV
SA1_UNIFORM/FJEN0/SA1.WAV
SA1_UNIFORM/FJHK0/SA1.WAV
SA1_UNIFORM/FJRP1/SA1.WAV
SA1_UNIFORM/FJSK0/SA1.WAV
SA1_UNIFORM/FKDE0/SA1.WAV
SA1_UNIFORM/FKSR0/SA1.WAV
SA1_UNIFORM/

In [5]:
# Iterate through the SA1.WAV files in the SA1_UNIFORM directory, find the shortest
# wav file, then cut all others to the same size.

SA1_base_dir = 'SA1_UNIFORM'
min_length = 100000
wav_dict = {}

for path, dirnames, filenames in os.walk('SA1_UNIFORM'):
    for dirname in dirnames:
        wav_path = SA1_base_dir + "/" + dirname + "/SA1.WAV"
        fs, data = wavfile.read(wav_path)
        wav_dict[dirname] = data
        if len(data) < min_length:
            min_length = len(data)
            
display(wav_dict)
display(min_length)

{'FAEM0': array([ 0, -9,  1, ..., -1, -1,  7], dtype=int16),
 'FAJW0': array([ 4, -5,  0, ..., -4,  1,  1], dtype=int16),
 'FALK0': array([-3,  9,  4, ..., -3, -9,  4], dtype=int16),
 'FALR0': array([-4, -3, -5, ...,  3,  1,  2], dtype=int16),
 'FAPB0': array([1, 0, 6, ..., 5, 5, 5], dtype=int16),
 'FBAS0': array([-6,  0, -3, ...,  2,  0,  1], dtype=int16),
 'FBCG1': array([ 2, -2,  2, ...,  9,  2, 24], dtype=int16),
 'FBCH0': array([ 4,  2,  2, ..., -1,  8, -1], dtype=int16),
 'FBJL0': array([  2,   1,  -1, ...,   1,   8, -20], dtype=int16),
 'FBLV0': array([ 5, 14, 19, ...,  5,  2,  5], dtype=int16),
 'FBMH0': array([ 3, 10, -5, ...,  3, -1,  9], dtype=int16),
 'FBMJ0': array([13, -1, -1, ..., -1,  1, -1], dtype=int16),
 'FCAG0': array([ 2,  0, -2, ...,  2,  2, 15], dtype=int16),
 'FCAJ0': array([ 3, 10, 10, ..., -5, -6, -3], dtype=int16),
 'FCDR1': array([7, 2, 3, ..., 5, 4, 5], dtype=int16),
 'FCEG0': array([ 3,  5,  3, ...,  0,  1, -1], dtype=int16),
 'FCJF0': array([ 1, -1,  2, .

37581

In [6]:
# Slice arrays for the minimum length

for key in wav_dict:
    wav_dict[key] = wav_dict[key][0 : min_length]

In [7]:
# First ten samples to train.

wav_dict_keys_1_10 = list(wav_dict.keys())[0:10]
wav_dict_values_1_10 = list(wav_dict.values())[0:10]

wav_dict_1_10 = dict(zip(wav_dict_keys_1_10, wav_dict_values_1_10))
wav_dict_1_10

{'FAEM0': array([   0,   -9,    1, ..., -423, -476, -502], dtype=int16),
 'FAJW0': array([  4,  -5,   0, ..., -46,  83, -93], dtype=int16),
 'FALK0': array([  -3,    9,    4, ..., -408, -642, -765], dtype=int16),
 'FALR0': array([  -4,   -3,   -5, ..., -248, -215, -165], dtype=int16),
 'FAPB0': array([ 1,  0,  6, ..., 47, 64, 87], dtype=int16),
 'FBAS0': array([ -6,   0,  -3, ..., 164, 180, 165], dtype=int16),
 'FBCG1': array([  2,  -2,   2, ..., 459, 448, 389], dtype=int16),
 'FBCH0': array([   4,    2,    2, ...,  319,  477, -813], dtype=int16),
 'FBJL0': array([   2,    1,   -1, ...,  134, -607, -111], dtype=int16),
 'FBLV0': array([   5,   14,   19, ..., 1860, 1512, 1063], dtype=int16)}

In [9]:
X_train = np.array(wav_dict_values_1_10)
print('X_trainn shape:\n', X_train.shape)
print('X_train:\n', X_train)
display(np.array(wav_dict_keys_1_10).reshape(-1,1 ))
onehot_encoder = OneHotEncoder(sparse = False, categories = 'auto')
y_train = onehot_encoder.fit_transform(np.array(wav_dict_keys_1_10).reshape(-1, 1))
print('y_train:\n', y_train)

X_trainn shape:
 (10, 37581)
X_train:
 [[   0   -9    1 ... -423 -476 -502]
 [   4   -5    0 ...  -46   83  -93]
 [  -3    9    4 ... -408 -642 -765]
 ...
 [   4    2    2 ...  319  477 -813]
 [   2    1   -1 ...  134 -607 -111]
 [   5   14   19 ... 1860 1512 1063]]


array([['FAEM0'],
       ['FAJW0'],
       ['FALK0'],
       ['FALR0'],
       ['FAPB0'],
       ['FBAS0'],
       ['FBCG1'],
       ['FBCH0'],
       ['FBJL0'],
       ['FBLV0']], dtype='<U5')

y_train:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [11]:

wnc = WaveNetClassifier((37581,), (10,), kernel_size = 2, dilation_depth = 9, n_filters = 40, task = 'classification')


__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
original_input (InputLayer)     (None, 37581)        0                                            
__________________________________________________________________________________________________
reshaped_input (Reshape)        (None, 37581, 1)     0           original_input[0][0]             
__________________________________________________________________________________________________
dilated_conv_1 (Conv1D)         (None, 37581, 40)    120         reshaped_input[0][0]             
__________________________________________________________________________________________________
dilated_conv_2_tanh (Conv1D)    (None, 37581, 40)    3240        dilated_conv_1[0][0]             
__________________________________________________________________________________________________
dilated_co

In [12]:
wnc.fit(X_train, y_train, epochs = 100, batch_size = 32, optimizer='adam', save=True, save_dir='results/')

Epoch 1/100
10/10 [==============================] - 21s 2s/step - loss: 2.3114 - acc: 0.1000

Epoch 00001: loss improved from inf to 2.31136, saving model to results/saved_wavenet_clasifier.h5
Epoch 2/100
10/10 [==============================] - 1s 127ms/step - loss: 2.9002 - acc: 0.1000

Epoch 00002: loss did not improve from 2.31136
Epoch 3/100
10/10 [==============================] - 1s 122ms/step - loss: 2.3034 - acc: 0.1000

Epoch 00003: loss improved from 2.31136 to 2.30340, saving model to results/saved_wavenet_clasifier.h5
Epoch 4/100
10/10 [==============================] - 1s 123ms/step - loss: 2.3046 - acc: 0.1000

Epoch 00004: loss did not improve from 2.30340
Epoch 5/100
10/10 [==============================] - 1s 122ms/step - loss: 2.3013 - acc: 0.1000

Epoch 00005: loss improved from 2.30340 to 2.30130, saving model to results/saved_wavenet_clasifier.h5
Epoch 6/100
10/10 [==============================] - 1s 121ms/step - loss: 2.3009 - acc: 0.1000

Epoch 00006: loss imp


Epoch 00046: loss did not improve from 0.93757
Epoch 47/100
10/10 [==============================] - 1s 122ms/step - loss: 0.9710 - acc: 0.6000

Epoch 00047: loss did not improve from 0.93757
Epoch 48/100
10/10 [==============================] - 1s 123ms/step - loss: 0.8741 - acc: 0.6000

Epoch 00048: loss improved from 0.93757 to 0.87414, saving model to results/saved_wavenet_clasifier.h5
Epoch 49/100
10/10 [==============================] - 1s 122ms/step - loss: 0.9513 - acc: 0.6000

Epoch 00049: loss did not improve from 0.87414
Epoch 50/100
10/10 [==============================] - 1s 122ms/step - loss: 0.6574 - acc: 0.8000

Epoch 00050: loss improved from 0.87414 to 0.65741, saving model to results/saved_wavenet_clasifier.h5
Epoch 51/100
10/10 [==============================] - 1s 124ms/step - loss: 0.8477 - acc: 0.9000

Epoch 00051: loss did not improve from 0.65741
Epoch 52/100
10/10 [==============================] - 1s 125ms/step - loss: 0.5632 - acc: 0.8000

Epoch 00052: loss

10/10 [==============================] - 1s 123ms/step - loss: 7.1100e-04 - acc: 1.0000

Epoch 00090: loss did not improve from 0.00070
Epoch 91/100
10/10 [==============================] - 1s 123ms/step - loss: 7.1870e-04 - acc: 1.0000

Epoch 00091: loss did not improve from 0.00070
Epoch 92/100
10/10 [==============================] - 1s 123ms/step - loss: 7.1755e-04 - acc: 1.0000

Epoch 00092: loss did not improve from 0.00070
Epoch 93/100
10/10 [==============================] - 1s 123ms/step - loss: 7.0333e-04 - acc: 1.0000

Epoch 00093: loss did not improve from 0.00070
Epoch 94/100
10/10 [==============================] - 1s 122ms/step - loss: 6.7511e-04 - acc: 1.0000

Epoch 00094: loss improved from 0.00070 to 0.00068, saving model to results/saved_wavenet_clasifier.h5
Epoch 95/100
10/10 [==============================] - 1s 123ms/step - loss: 6.3492e-04 - acc: 1.0000

Epoch 00095: loss improved from 0.00068 to 0.00063, saving model to results/saved_wavenet_clasifier.h5
Epoch 9

In [15]:
# Copy the SA2.WAV files with the identifier folders to SA2_UNIFORM directory.

SA2_base_dir = 'SA2_UNIFORM'

for path, dirname, filenames in os.walk('TRAIN_WAV'):
    for filename in filenames:
        if filename.endswith("SA2.WAV"):
            file_path = os.path.join(path, filename)
            path_array = file_path.split(os.sep)
            path_array[0] = SA2_base_dir
            try:
                os.makedirs(path_array[0] + "/" + path_array[-2])
            except FileExistsError:
                # directory already exists
                pass
            new_path = path_array[0] + "/" + path_array[-2] + "/" + filename
            print(new_path)
            copyfile(file_path, new_path)

SA2_UNIFORM/FCJF0/SA2.WAV
SA2_UNIFORM/FDAW0/SA2.WAV
SA2_UNIFORM/FDML0/SA2.WAV
SA2_UNIFORM/FECD0/SA2.WAV
SA2_UNIFORM/FETB0/SA2.WAV
SA2_UNIFORM/FJSP0/SA2.WAV
SA2_UNIFORM/FKFB0/SA2.WAV
SA2_UNIFORM/FMEM0/SA2.WAV
SA2_UNIFORM/FSAH0/SA2.WAV
SA2_UNIFORM/FSJK1/SA2.WAV
SA2_UNIFORM/FSMA0/SA2.WAV
SA2_UNIFORM/FTBR0/SA2.WAV
SA2_UNIFORM/FVFB0/SA2.WAV
SA2_UNIFORM/FVMH0/SA2.WAV
SA2_UNIFORM/MCPM0/SA2.WAV
SA2_UNIFORM/MDAC0/SA2.WAV
SA2_UNIFORM/MDPK0/SA2.WAV
SA2_UNIFORM/MEDR0/SA2.WAV
SA2_UNIFORM/MGRL0/SA2.WAV
SA2_UNIFORM/MJEB1/SA2.WAV
SA2_UNIFORM/MJWT0/SA2.WAV
SA2_UNIFORM/MKLS0/SA2.WAV
SA2_UNIFORM/MKLW0/SA2.WAV
SA2_UNIFORM/MMGG0/SA2.WAV
SA2_UNIFORM/MMRP0/SA2.WAV
SA2_UNIFORM/MPGH0/SA2.WAV
SA2_UNIFORM/MPGR0/SA2.WAV
SA2_UNIFORM/MPSW0/SA2.WAV
SA2_UNIFORM/MRAI0/SA2.WAV
SA2_UNIFORM/MRCG0/SA2.WAV
SA2_UNIFORM/MRDD0/SA2.WAV
SA2_UNIFORM/MRSO0/SA2.WAV
SA2_UNIFORM/MRWS0/SA2.WAV
SA2_UNIFORM/MTJS0/SA2.WAV
SA2_UNIFORM/MTPF0/SA2.WAV
SA2_UNIFORM/MTRR0/SA2.WAV
SA2_UNIFORM/MWAD0/SA2.WAV
SA2_UNIFORM/MWAR0/SA2.WAV
SA2_UNIFORM/

SA2_UNIFORM/FLAG0/SA2.WAV
SA2_UNIFORM/FMJU0/SA2.WAV
SA2_UNIFORM/FPAD0/SA2.WAV
SA2_UNIFORM/FRJB0/SA2.WAV
SA2_UNIFORM/FSBK0/SA2.WAV
SA2_UNIFORM/FSDJ0/SA2.WAV
SA2_UNIFORM/FSGF0/SA2.WAV
SA2_UNIFORM/FTAJ0/SA2.WAV
SA2_UNIFORM/MABC0/SA2.WAV
SA2_UNIFORM/MAJP0/SA2.WAV
SA2_UNIFORM/MBMA1/SA2.WAV
SA2_UNIFORM/MCAE0/SA2.WAV
SA2_UNIFORM/MDRD0/SA2.WAV
SA2_UNIFORM/MEAL0/SA2.WAV
SA2_UNIFORM/MEJL0/SA2.WAV
SA2_UNIFORM/MESJ0/SA2.WAV
SA2_UNIFORM/MJRK0/SA2.WAV
SA2_UNIFORM/MKES0/SA2.WAV
SA2_UNIFORM/MKLN0/SA2.WAV
SA2_UNIFORM/MMDB0/SA2.WAV
SA2_UNIFORM/MPGR1/SA2.WAV
SA2_UNIFORM/MRMB0/SA2.WAV
SA2_UNIFORM/MRXB0/SA2.WAV
SA2_UNIFORM/MSAT1/SA2.WAV
SA2_UNIFORM/MSDS0/SA2.WAV
SA2_UNIFORM/MSJK0/SA2.WAV
SA2_UNIFORM/MSMR0/SA2.WAV
SA2_UNIFORM/MSVS0/SA2.WAV
SA2_UNIFORM/MTJU0/SA2.WAV
SA2_UNIFORM/MTXS0/SA2.WAV
SA2_UNIFORM/FBLV0/SA2.WAV
SA2_UNIFORM/FCJS0/SA2.WAV
SA2_UNIFORM/FCRZ0/SA2.WAV
SA2_UNIFORM/FJEN0/SA2.WAV
SA2_UNIFORM/FJHK0/SA2.WAV
SA2_UNIFORM/FJRP1/SA2.WAV
SA2_UNIFORM/FJSK0/SA2.WAV
SA2_UNIFORM/FKDE0/SA2.WAV
SA2_UNIFORM/

In [17]:
# Iterate through the SA2.WAV files in the SA2_UNIFORM directory, and cut them all to
# min(SA1) = min_length size.

SA2_base_dir = 'SA2_UNIFORM'
wav_dict2 = {}

for path, dirnames, filenames in os.walk('SA2_UNIFORM'):
    for dirname in dirnames:
        wav_path = SA2_base_dir + "/" + dirname + "/SA2.WAV"
        fs, data = wavfile.read(wav_path)
        wav_dict2[dirname] = data[0 : min_length]

In [23]:
# First ten samples to test.

wav_dict2_keys_1_10 = list(wav_dict2.keys())[0:10]
wav_dict2_values_1_10 = list(wav_dict2.values())[0:10]

wav_dict2_1_10 = dict(zip(wav_dict2_keys_1_10, wav_dict2_values_1_10))
wav_dict2_1_10

{'FAEM0': array([ 4,  1, -1, ...,  1,  6, -6], dtype=int16),
 'FAJW0': array([24, -6,  5, ..., 61, 78, 59], dtype=int16),
 'FALK0': array([  -1,   -2,   -1, ..., -200, -163, -131], dtype=int16),
 'FALR0': array([  0,   1,   2, ..., -54, -57, -43], dtype=int16),
 'FAPB0': array([  4,   3,   4, ..., 228, 505, 617], dtype=int16),
 'FBAS0': array([ -1,   2,   0, ..., 361, 514, 604], dtype=int16),
 'FBCG1': array([   4,    5,    4, ..., -706, -742, -764], dtype=int16),
 'FBCH0': array([  4,   2,  -3, ...,   3, -24, -26], dtype=int16),
 'FBJL0': array([  3,  -1,   3, ...,  48, 115, 149], dtype=int16),
 'FBLV0': array([   2,   -2,    0, ..., -300, -443, -556], dtype=int16)}

In [40]:
# Evaluate model.

X_test = np.array(wav_dict2_values_1_10)
y_test = y_train

model = wnc.get_model()

res = model.evaluate(X_test, y_test, verbose = 1)

display(model.metrics_names)
display(res)

10/10 [==============================] - 0s 45ms/step


['loss', 'acc']

[7.300926208496094, 0.30000001192092896]

In [59]:
# Predictions.

y_pred = wnc.predict(X_test)

args = []
for pred in y_pred:
    args.append(np.argmax(pred))
    
args

[5, 3, 3, 3, 4, 3, 6, 6, 5, 6]